### ISSUE TITLE
ngrok tunnel incorrect?

### ISSUE THREAD

**Issue by Frotty** [ivangfr/socketio-express-phaser3#6]
Hi,
in your readme you suggest to use ngrok to tunnel the phase frontend for other players.
However this doesn't make any sense, because when other players load the frontend it will still try to connect to "localhost" on their machine for the server, but of course the server isn't running on their localhost.
I'm pretty sure the only way this could work, would be to tunnel the server and the game and then put the tunneled URL as server location for the game.
However I was not able to get this to work with ngrok, the websocket connection did not want to work.

**Comment by Frotty** [comment]
Ok my mistake, in your project is server is serving the phaser game as well.
I was trying to make this work with this other project https://github.com/JamesSkemp/phaser-3-vsc-typescript-nodejs
But there server and game are served independently.
However I am still wondering how this works by just using `io`.

**Comment by Frotty** [comment]
Ok I got it. I added the static serving to to my project which fixed the problems, sorry for the ticket.

**Comment by ivangfr** [comment]
No problem @Frotty I am glad to hear that you were able to fix the problems!
